### ISSUE TITLE
Use [[ -n "$whatever" ]] rather than [[ "$whatever" ]]

### ISSUE THREAD

**Issue by stuartpb** [progrium/bashstyle#25]
Okay, so, in Bash, with double-brace tests, this will never *actually* be misinterpreted.

However:

- Using `-n` makes your test have an operator, just like *every other test* will, making it perfectly clear that this wasn't, say, somebody forgetting to add an operator/operand to the test.
- In older shell constructs like the single-brace test (which your tests could be converted to if somebody copies a snippet of it to convert to zsh or something), `[ "$whatever" ...` is how you specify a *variable test operator* (yikes!), and thus this opens up a potential channeling attack (see #18).

**Comment by progrium** [comment]
Mmmm, it kind of goes both ways. I like the simplicity of not using `-n` because for people that forget all the operators it's actually more readable. Esp if they know they can not use `-n` for the same thing they'll wonder "why is -n being used? what does it mean again?"

On top of that, I'm trying to focus on Bash and double-brace tests. So if your plan is to be portable to non-Bash shells, this is important, but not what my guide is optimizing for.

**Comment by stuartpb** [comment]
There's `[[ ! -z "whatever" ]]` if you're trying to be minimal with operators.

I think that, on the scale of "making people remember hard things", `[[ ! -z` is the best way to represent "string not null", but `[[ -n` is *less* of a burden to comprehend than `[[ "$string" ]]`. `-n` involves remembering one more test flag (which, when not clear from context/comments, are always one quick Google search away): `[[ "$variable" ]]` requires understanding that, unlike *commands* (including the single-brace `[` test), expanding the first argument to `[[` is *not* equivalent to substituting the content of the string, and double-brace has this whole special syntax that applies to how it evaluates arguments that doesn't apply for anything else.

And, to go back to my initial point, a forgotten operand is easier to type by accident.
